//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Siskon_EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public string Plate { get; set; }
        public string Nickname { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Year { get; set; }
        public bool IsActive { get; set; }
        public string Type { get; set; }
        public string Color { get; set; }
        public long Id { get; set; }
    }
}
